-- Create table for Midtrans transaction logs
-- Run this in Supabase SQL Editor

create table if not exists public.midtrans_transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  order_id text not null,
  package_id text,
  gross_amount integer not null,
  coins_added integer not null,
  transaction_status text not null,
  payment_type text,
  fraud_status text,
  midtrans_signature text,
  raw_payload jsonb not null,
  created_at timestamp with time zone default now()
);

create index if not exists midtrans_transactions_user_id_idx
  on public.midtrans_transactions (user_id);

create index if not exists midtrans_transactions_order_id_idx
  on public.midtrans_transactions (order_id);

create index if not exists midtrans_transactions_created_at_idx
  on public.midtrans_transactions (created_at desc);
